#ifndef KT_SYSTEM_MACRO_COMMON_H
#define KT_SYSTEM_MACRO_COMMON_H

#define SYSTEM_PLATFORM_CPU_X86                     1
#define SYSTEM_PLATFORM_CPU_IMX6                    2
#define SYSTEM_PLATFORM_CPU_M3N                     3
#define SYSTEM_PLATFORM_CPU_S32V                    4

#define SYSTEM_PLATFORM_OS_UBUNTU                   1
#define SYSTEM_PLATFORM_OS_WINDOWS                  2
#define SYSTEM_PLATFORM_OS_LINUX                    3

#define __PLATFORM_SIMULATE_CAMERA__                0
#define __PLATFORM_SIMULATE_ADCU_PC__               0

#ifdef PLATFORM_IMX6
#define __PLATFORM__CPU__CC__ SYSTEM_PLATFORM_CPU_IMX6
#define __PLATFORM__OS__CC__    SYSTEM_PLATFORM_OS_LINUX
#else
#ifdef PLATFORM_S32V
#define __PLATFORM__CPU__CC__ SYSTEM_PLATFORM_CPU_S32V
#define __PLATFORM__OS__CC__    SYSTEM_PLATFORM_OS_LINUX
#else
#if __PLATFORM_SIMULATE_ADCU_PC__
#define __PLATFORM__CPU__CC__   SYSTEM_PLATFORM_CPU_M3N
#else
#define __PLATFORM__CPU__CC__   SYSTEM_PLATFORM_CPU_X86
#define __PLATFORM__OS__CC__    SYSTEM_PLATFORM_OS_UBUNTU
#endif
#endif
#endif

#define CHECK_PLATFORM_CPU(A)   (__PLATFORM__CPU__CC__  == A)
#define CHECK_PLATFORM_OS(A)    (__PLATFORM__OS__CC__   == A)

#define CHECK_PLATFORM_PC (__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_X86)
#define CHECK_PLATFORM_PC_UBUNTU ((__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_X86) && (__PLATFORM__OS__CC__ == SYSTEM_PLATFORM_OS_UBUNTU))
#define CHECK_PLATFORM_PC_WINDOWS ((__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_X86) && (__PLATFORM__OS__CC__ == SYSTEM_PLATFORM_OS_WINDOWS))
#define CHECK_PLATFORM_IMX6 ((__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_IMX6) && (__PLATFORM__OS__CC__ == SYSTEM_PLATFORM_OS_LINUX))
#define CHECK_PLATFORM_S32V ((__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_S32V) && (__PLATFORM__OS__CC__ == SYSTEM_PLATFORM_OS_LINUX))
#define CHECK_PLATFORM_ARM (CHECK_PLATFORM_IMX6 || CHECK_PLATFORM_S32V)
#define CHECK_PLATFORM_RCAR (__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_M3N)
#define CHECK_PLATFORM_SIMULATE_RCAR ((__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_M3N) && (__PLATFORM_SIMULATE_ADCU_PC__))
#define CHECK_PLATFORM_N_SIMULATE_RCAR ((__PLATFORM__CPU__CC__ == SYSTEM_PLATFORM_CPU_M3N) && (__PLATFORM_SIMULATE_ADCU_PC__ == 0))

#endif